# Generated by Django 4.0.1 on 2022-02-16 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailyStockData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=5)),
                ('date', models.DateField()),
                ('open', models.DecimalField(decimal_places=4, max_digits=10)),
                ('high', models.DecimalField(decimal_places=4, max_digits=10)),
                ('low', models.DecimalField(decimal_places=4, max_digits=10)),
                ('close', models.DecimalField(decimal_places=4, max_digits=10)),
                ('volume', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('ticker', models.CharField(max_length=5, primary_key=True, serialize=False, unique=True)),
                ('company_info', models.CharField(max_length=120)),
            ],
        ),
    ]
