# Generated by Django 4.0.1 on 2022-04-21 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailyStockData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=5)),
                ('date', models.DateField()),
                ('open', models.DecimalField(decimal_places=4, max_digits=10)),
                ('high', models.DecimalField(decimal_places=4, max_digits=10)),
                ('low', models.DecimalField(decimal_places=4, max_digits=10)),
                ('close', models.DecimalField(decimal_places=4, max_digits=10)),
                ('volume', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('ticker', models.CharField(max_length=5, primary_key=True, serialize=False, unique=True)),
                ('company_info', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='StockRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=5)),
                ('recommendation', models.CharField(max_length=5)),
                ('buy_price', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('buy_cycle', models.BooleanField(default=False)),
                ('total_return', models.DecimalField(decimal_places=8, default=0, max_digits=12)),
                ('number_cycles', models.IntegerField(default=0)),
                ('buy_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='WatchedStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=5)),
                ('username', models.CharField(max_length=100)),
            ],
        ),
    ]
