# Generated by Django 4.0.1 on 2022-04-04 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=5)),
                ('recommendation', models.CharField(max_length=5)),
                ('buy_price', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('buy_cycle', models.BooleanField(default=False)),
                ('average_return', models.DecimalField(decimal_places=8, default=0, max_digits=10)),
                ('number_cycles', models.IntegerField(default=0)),
            ],
        ),
    ]
