# Generated by Django 4.0.1 on 2022-04-21 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockBuyCycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=5)),
                ('buy_date', models.DateField()),
                ('sell_date', models.DateField()),
                ('total_return', models.DecimalField(decimal_places=8, default=0, max_digits=12)),
            ],
        ),
    ]
